# Generated by Django 4.2.7 on 2024-02-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_marketplace', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
