# Generated by Django 4.2.7 on 2024-02-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_marketplace', '0007_remove_order_item_price_remove_order_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('necitit', 'Necitit'), ('rezolvat', 'Rezolvat')], default='necitit', max_length=10)),
                ('receiving_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
