# Generated by Django 4.2.7 on 2024-02-07 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_marketplace', '0008_mesaj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesaj',
            name='surname',
        ),
    ]
