# Generated by Django 4.2.7 on 2024-02-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_marketplace', '0010_bookreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookReview',
        ),
    ]
